// produtos.js
export const produtosMock = [
    { id: "1", nome: "Kimono Ultra Light A1", preco: 489.90, desc: "Trançado leve para competição.", img: "https://m.media-amazon.com/images/I/61QuXkynwyL._AC_UF1000,1000_QL80_.jpg", category: "Kimono", sizes: ["A1", "A2", "A3", "A4"], colors: ["Branco", "Preto", "Azul"] },
    { id: "2", nome: "Faixa Preta Competition", preco: 95.00, desc: "12 costuras oficiais.", img: "./assets/bjjblack.jpg", category: "Faixa", sizes: ["A1", "A2", "A3", "A4"], colors: ["Branco", "Preto", "Azul"] },
    { id: "3", nome: "Rashguard Armor Black", preco: 149.90, desc: "Proteção UV e compressão.", img: "./assets/rash.jpg", category: "Rashguard", sizes: ["P", "M", "G", "GG"], colors: ["Preto", "Cinza"] },
    { id: "4", nome: "Bolsa de Treino 40L", preco: 210.00, desc: "Espaço para 2 kimonos.", img: "./assets/mochila.jpg", category: "Acessorio", sizes: ["Único"], colors: ["Preto"] },
    { id: "5", nome: "Kimono Blue Warrior", preco: 520.00, desc: "Edição limitada azul royal.", img: "./assets/kimono.jpg", category: "Kimono", sizes: ["A1", "A2", "A3", "A4"], colors: ["Branco", "Preto", "Azul"] },
    { id: "6", nome: "Shorts No-Gi Stealth", preco: 129.00, desc: "Abertura lateral para mobilidade.", img: "./assets/bermuda.jpg", category: "Acessorio", sizes: ["P", "M", "G", "GG"], colors: ["Preto", "Azul"] },
    { id: "7", nome: "Kneepad Gel Pro", preco: 85.00, desc: "Proteção extra para os joelhos.", img: "./assets/joelheira.jpg", category: "Acessorio", sizes: ["P", "M", "G"], colors: ["Preto"] },
    { id: "8", nome: "Chinelo BJJ Style", preco: 55.00, desc: "Conforto pós-treino.", img: "./assets/chinelo.jpg", category: "Acessorio", sizes: ["36-37", "38-39", "40-41", "42-43"], colors: ["Preto", "Branco"] },
    { id: "9", nome: "Kimono Samurai Edition Branco", preco: 699.90, desc: "Edição limitada com bordados samurai e tecido premium ultra-resistente.", img: "https://cdn.shopify.com/s/files/1/1229/2604/files/ISAMI_White_with_patches-horz_large.jpg?9263716183051758241", category: "Kimono", sizes: ["A1", "A2", "A3", "A4"], colors: ["Branco"] },
    { id: "10", nome: "Spats Compression Tao Black", preco: 139.90, desc: "Calça de compressão No-Gi com design tao para maior mobilidade.", img: "http://www.shogunfight.com/cdn/shop/products/Screen_Shot_2017-03-01_at_2.25.19_PM_1024x1024.jpg?v=1546010310", category: "Acessorio", sizes: ["P", "M", "G", "GG"], colors: ["Preto"] },
    { id: "11", nome: "Protetor de Orelha Elite Guard", preco: 149.90, desc: "Headgear ajustável para prevenir orelha de couve-flor.", img: "https://m.media-amazon.com/images/I/01UwfHrld%2BL._TSa%7Csize%3A1910%2C1000%7Cformat%3A%28A%2Cf%2Cb%2Cd%2Cpi%2Cpl%2Co%29%7Cb-src%3A61Cd2rJZgRL.png%7Cb-pos%3A0%2C0%2C1910%2C1000%7Cpi-src%3A7170MstW4CL.jpg%7Cpi-pos%3A1000%2C100%2C840%2C840.json", category: "Acessorio", sizes: ["Único"], colors: ["Preto"] },
    { id: "12", nome: "Protetor Bucal Custom Fit", preco: 89.90, desc: "Protetor bucal moldável de alto impacto para treinos pesados.", img: "https://m.media-amazon.com/images/I/71bbGYqXfDL._AC_UF1000,1000_QL80_.jpg", category: "Acessorio", sizes: ["Único"], colors: ["Preto", "Transparente"] },
    { id: "13", nome: "Mochila Gear Expandable 60L", preco: 319.90, desc: "Mochila/duffel expansível com múltiplos compartimentos para equipamentos.", img: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/36525f96-d1c9-4240-bd2e-3932595fa5b1.__CR0,0,600,450_PT0_SX600_V1___.jpg", category: "Acessorio", sizes: ["Único"], colors: ["Preto"] },
    { id: "14", nome: "Tornozeleira Compression Pro", preco: 99.90, desc: "Suporte para tornozelo com compressão para prevenção de lesões.", img: "https://www.donjoystore.com/media/catalog/product/cache/25db35f0819453b15c051664bd2c0f47/d/o/donjoy-performance-pod-black-ankle-brace.jpg", category: "Acessorio", sizes: ["P", "M", "G"], colors: ["Preto"] },
    { id: "15", nome: "Fita para Dedos Athletic Pack", preco: 49.90, desc: "Pacote com 8 rolos de fita atlética para proteção dos dedos.", img: "https://m.media-amazon.com/images/I/71RSHUB6x5L._AC_UF1000,1000_QL80_.jpg", category: "Acessorio", sizes: ["Único"], colors: ["Preto"] },
    { id: "16", nome: "Rashguard Feminino Kraken Long Sleeve", preco: 179.90, desc: "Rashguard manga longa feminino com design kraken exclusivo.", img: "https://www.ravenfightwear.com/cdn/shop/files/kraken-jiu-jitsu-club-rashguard-womens-875673.jpg?v=1723038710&width=1445", category: "Rashguard", sizes: ["P", "M", "G", "GG"], colors: ["Preto"] },
    { id: "17", nome: "Moletom BJJ Rapid Hoodie", preco: 199.90, desc: "Moletom confortável com capuz para pós-treino ou casual.", img: "https://www.rolljunkie.com/cdn/shop/files/rapid_bjj_hoodie_front2.jpg?v=1710967724&width=1200", category: "Acessorio", sizes: ["P", "M", "G", "GG"], colors: ["Preto"] },
    { id: "18", nome: "Patch Lifestyle Gorilla", preco: 29.90, desc: "Patch bordado gorilla para customizar seu kimono.", img: "https://i.etsystatic.com/14615478/c/1052/836/0/184/il/3130fc/4184364178/il_340x270.4184364178_q59t.jpg", category: "Acessorio", sizes: ["Único"], colors: ["Preto"] }
];